### ISSUE TITLE
Title menu logo doesn't work properly in 1.19.4

### ISSUE THREAD

**Issue by SirenGlitch** [catppuccin/minecraft#36]
# Need I say more?

![image](https://github.com/catppuccin/minecraft/assets/110285018/a4a356a0-1d79-40b6-91c1-1c49dd676aae)

**Comment by JustLetterV** [comment]
Hi, I can't reproduce this. Which resourcepack version are you using? I've tested the latest version (1.3.0+1.19.4) for 1.19.4 and it seems to be working correctly

**Comment by SirenGlitch** [comment]
Had a thought, the launcher I use (Prism Launcher) doesn't seem to check the resource pack version properly, meaning that I'd be getting the latest release to modrinth, rather then latest for that game version. Do you mind checking the latest resourcepack version and seeing if that produces the same result as I got?

**Comment by JustLetterV** [comment]
Latest version for 1.19.4 shouldn't have the issue, but latest version which is for 1.20.6 has the same result, because it's not supposed to be used for Minecraft 1.19.4. If you download latest version for 1.19.4 [here](https://modrinth.com/resourcepack/catppuccin-ui/versions?g=1.19.4) the issue shouldn't persist

**Comment by JustLetterV** [comment]
Also forgot to mention: I suggest manually updating this resourcepack. The way i manage versions (different flavors & accent colors) makes it pretty much impossible for launchers to correctly detect the correct version of the pack

**Comment by SirenGlitch** [comment]
Yep, good to know. Will change version now
